export default [
  { name: 'Argentina', value: '' },
  { name: 'Ciudad de Buenos Aires', value: 'Capital Federal' },
  { name: 'Buenos Aires', value: 'Buenos Aires' },
  { name: 'Catamarca', value: 'Catamarca' },
  { name: 'Chaco', value: 'Chaco' },
  { name: 'Chubut', value: 'Chubut' },
  { name: 'Córdoba', value: 'Córdoba' },
  { name: 'Corrientes', value: 'Corrientes' },
  { name: 'Entre Ríos', value: 'Entre Ríos' },
  { name: 'Formosa', value: 'Formosa' },
  { name: 'Jujuy', value: 'Jujuy' },
  { name: 'La Pampa', value: 'La Pampa' },
  { name: 'La Rioja', value: 'La Rioja' },
  { name: 'Mendoza', value: 'Mendoza' },
  { name: 'Misiones', value: 'Misiones' },
  { name: 'Neuquén', value: 'Neuquén' },
  { name: 'Río Negro', value: 'Río Negro' },
  { name: 'Salta', value: 'Salta' },
  { name: 'San Juan', value: 'San Juan' },
  { name: 'San Luis', value: 'San Luis' },
  { name: 'Santa Cruz', value: 'Santa Cruz' },
  { name: 'Santa Fé', value: 'Santa Fé' },
  { name: 'Santiago del Estero', value: 'Santiago del Estero' },
  { name: 'Tierra del Fuego', value: 'Tierra del Fuego' },
  { name: 'Tucumán', value: 'Tucumán' }
];
