export const SEARCH_TERM_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';
export const SELECT_LOCATION_INPUT_CHANGE = 'SELECT_LOCATION_INPUT_CHANGE';

export const SEARCH_BUTTON_PRESSED = 'SEARCH_BUTTON_PRESSED';
