export const SEARCH_TERM_INPUT_CHANGE = 'SEARCH_INPUT_CHANGE';
export const SELECT_LOCATION_INPUT_CHANGE = 'SELECT_LOCATION_INPUT_CHANGE';

export const SEARCH_BUTTON_PRESSED = 'SEARCH_BUTTON_PRESSED';

export const ADVERTS_DATE_FILTER_SETTED = 'ADVERTS_DATE_FILTER_SETTED';

export const ADVERTS_FETCHED = 'ADVERTS_FETCHED';
export const ADVERTS_GET_NEXT_PAGE = 'ADVERTS_GET_NEXT_PAGE';
export const ERROR_FETCHING_ADVERTS_DATA = 'ERROR_FETCHING_ADVERTS_DATA';

export const INCREMENT_PAGE = 'INCREMENT_PAGE ';
